### ISSUE TITLE
[화면 종횡비]

### ISSUE THREAD

**Issue by AmitaWhite** [AmitaWhite/VideoEditorPro#3]
비디오가 보일 화면 크기를 정하는 중 입니다.
화면 종횡비를 어디를 기준으로 맞춰 작성해야 할지 논의가 필요할 것 같습니다.

* 현재 고민 : 외부 Box Size 에 따라 동적으로 변화 시킬지 특정 화면비를 우선적으로 고정하여 진행할지 의견 주시면 감사하겠습니다.

**Comment by DaYoung-woo** [comment]
개인적으로 태블릿 크기에 맞춰 비디오의 최대 크기를 지정하는 편이 좋다고 생각합니다.
비디오의 크기가 제한 없이 커지면 UI상으로 예쁘지 않아보입니다...

**Comment by DaYoung-woo** [comment]
@AmitaWhite 
개인적으로 태블릿 크기에 맞춰 비디오의 최대 크기를 지정하는 편이 좋다고 생각합니다.
비디오의 크기가 제한 없이 커지면 UI상으로 예쁘지 않아보입니다...

**Comment by AmitaWhite** [comment]
확인 했습니다. 아래 화면비에 맞춰진행하겠습니다.
* 태블릿 화면비 : 768 * 667
